version: 0.2
 
env:
  variables:
    AWS_REGION: us-east-1
    ECR_REGISTRY: 763944546746.dkr.ecr.us-east-1.amazonaws.com
    EKS_CLUSTER_NAME: my-cluster
 
phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
  post_build:
    commands:
      - echo Configuring kubectl...
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
      - export KUBECONFIG=/root/.kube/config
      - aws sts get-caller-identity
      - kubectl config get-contexts
      - kubectl version
      - echo Deploying to EKS...
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
