version: 0.2
 
env:
  variables:
    AWS_REGION: us-east-1
    ECR_REGISTRY: 763944546746.dkr.ecr.us-east-1.amazonaws.com
    EKS_CLUSTER_NAME: my-cluster
 
phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
  build:
    commands:
      - echo Building Docker images...
      - docker build -t app1 ./app1
      - docker tag app1:latest $ECR_REGISTRY/app1-repo:latest
      - docker build -t app2 ./app2
      - docker tag app2:latest $ECR_REGISTRY/app2-repo:latest
  post_build:
    commands:
      - echo Pushing Docker images...
      - docker push $ECR_REGISTRY/app1-repo:latest
      - docker push $ECR_REGISTRY/app2-repo:latest
      - echo Configuring kubectl...
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
      - echo Deploying to EKS...
      - kubectl apply -f deployments/
